project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - talks.qmd
    - service.qmd
website:
  title: "Wensen Ma"
  site-url: https://wensen-ma.github.io/
  description: "Representation learning, self-supervised learning, generative learning, and the theory of language models."
  favicon: misc/info/favicon.jpg
  repo-url: https://github.com/wensen-ma/wensen-ma.github.io
  navbar:
    title: "Wensen Ma"
    background: light
    collapse-below: lg
    search: false
    right:
      - text: Research
        href: index.qmd#research
      - text: Publications
        href: index.qmd#publications
      - text: Talks
        href: talks.qmd
      - text: Academic Service
        href: service.qmd
  page-footer:
    left: "© 2025–2026 Wensen Ma"
    right:
      - text: Google Scholar
        href: https://scholar.google.com/citations?user=LQnVgkQAAAAJ&hl=en
      - text: GitHub
        href: https://github.com/vincen-github

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: false
    anchor-sections: true
    smooth-scroll: true
    lang: en
